### ISSUE TITLE
Incorrect and Missing steps for Android Emulator on MacOS

### ISSUE THREAD

**Issue by nicolemal** [dotnet/docs-maui#2267]
### Type of issue

Typo

### Description

the wiki needs to be fixed here: https://learn.microsoft.com/en-us/dotnet/maui/get-started/first-app?view=net-maui-8.0&pivots=devices-windows&tabs=visual-studio-code#choose-your-target-device
1. There is a typo in a command that needs the "" in it. This command: ./sdkmanager --install system-images;android-33;google_apis;x86_64
should be:
./sdkmanager --install **"**system-images;android-33;google_apis;x86_64**"**
2. There is a missing step for using the android emulator. You can not simply click run on the debugger on visual studio code, else you get a message "error XA0010: Selected device is not running.". You must first open a terminal and run ./emulator -avd MyAndroidVirtualDevice-_API33 -netdelay none -netspeed full  from the directory "/Users/janedoe/Library/Android/sdk/emulator". THEN you can run the program with visual studio code.
3. It would be nice to have prerequisite steps on how to set up java for your MAUI app (i.e. after installing the right version of java using curl -OL https://aka.ms/download-jdk/microsoft-jdk-17-macOS-x64.tar.gz, use cmd+shift+p to open the visual studio code command palette -> NET MAUI: Configure Android -> Set Java SDK path). It took me some fumbling around to figure it out

Happy to report the Android emulator is now running on my MacBook :)

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/get-started/first-app?view=net-maui-8.0&pivots=devices-windows&tabs=visual-studio-code#choose-your-target-device

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md

### Document Version Independent Id

e77ba6a7-e59d-1e1e-52e1-935f98a985cf

### Article author

@davidbritch

### Metadata

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment]
Hi @nicolemal 

(1) + (2) were addressed with a PR that went live a few days ago.

(3) is taken care of via the installation doc.

**Comment by nicolemal** [comment]
I do not see 2 being addressed in the new docs

These tidbits are good to make the product as usable as possible for customers :)

**Comment by davidbritch** [comment]
The doc uses `avdmanager` to install the emulator.

**Comment by fernlance** [comment]
I'm still getting (2) above - using VSCode on M2 w/ .NET 8

> There is a missing step for using the android emulator. You can not simply click run on the debugger on visual studio code, else you get a message "error XA0010: Selected device is not running.". 

  Determining projects to restore...
  All projects are up-to-date for restore.
  Including assemblies for Hot Reload support
  MauiApp1 -> /Users/fernlance/Documents/GitHub/fernlance/MauiApp1/bin/Debug/net8.0-android/MauiApp1.dll
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/34.0.138/tools/Xamarin.Android.Common.Debugging.targets(678,5): error XA0010: Selected device is not running. [/Users/fernlance/Documents/GitHub/fernlance/MauiApp1/MauiApp1.csproj::TargetFramework=net8.0-android]

Build FAILED.

/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/34.0.138/tools/Xamarin.Android.Common.Debugging.targets(678,5): error XA0010: Selected device is not running. [/Users/fernlance/Documents/GitHub/fernlance/MauiApp1/MauiApp1.csproj::TargetFramework=net8.0-android]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:02.18

When running the following command (from within the Android SDK path indicated below) prior to launch I get no issues and the app launches inside the chosen emulator
`./emulator -avd tablet_m-dpi_10_1in_-_api_33`

Android Environment:
	Android SDK path: '/Users/fernlance/Library/Developer/Xamarin/android-sdk-macosx'
 
	Required components:
	- jdk: installed version '17.0.12' path: '/Library/Java/JavaVirtualMachines/microsoft-17.jdk/Contents/Home'
			Detected location (Visual Studio): /Library/Java/JavaVirtualMachines/microsoft-11.jdk/Contents/Home
			Detected location: /Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home
	- platforms/android-34: installed version '1'
	- build-tools/34.0.0: installed version '34.0.0'
	- platform-tools: installed version '35.0.2'
	- cmdline-tools/11.0: installed version '11.0'
 
	Optional components:
	- emulator: installed version '32.1.14'

![image](https://github.com/user-attachments/assets/aedef165-1e7a-4a8d-b952-29975e285608)

**Comment by nicholasyin** [comment]
I encountered the same 'selected device is not running' error, with no clue at all. It turns out if I create the emulator using the GUI manager from Android Studio, vscode can auto launch the emulator and run. But if I create the emulator using the avdmanager command line, vscode will report this error.
